Repository Bus42/Configurable-Credits, pull requests merged in 2025-04, with the labels that each got.

#22 Trigger a Streamer.bot action on credits end!
  .vscode/settings.json
  changelog.md
  index.html
  src/js/config.js
  src/js/credits.js
  src/js/index.js
Labels: enhancement

#29 Update README.md
  README.md
Labels: documentation

#30 Adds a Requirements section to README
  README.md
  changelog.md
Labels: documentation

#32 Refactor for Streamer.bot client API
  .vscode/settings.json
  CONTRIBUTING.MD
  README.md
  changelog.md
  index.html
  src/js/client.js
  src/js/config.js
  src/js/credits.js
Labels: enhancement

#33 Refactor for Streamer.bot client API (#32)
  .vscode/settings.json
  CONTRIBUTING.MD
  README.md
  changelog.md
  index.html
  src/js/client.js
  src/js/config.js
  src/js/credits.js
Labels: documentation, enhancement
